#!/usr/bin/env python3
"""
Volatility Index 75 (V75) Expert Advisor for Deriv Trading Bot
Implements specialized trading strategies for the V75 synthetic index.

V75 Characteristics:
- High volatility synthetic index (75% volatility)
- 24/7 trading availability
- No market gaps
- Tick-based price movements
- Ideal for scalping and momentum strategies

Author: Trading Bot EA System
"""

import logging
import asyncio
import numpy as np
from collections import deque
from dataclasses import dataclass, field
from typing import Optional, Callable, Dict, Any, List
from datetime import datetime, timedelta
from enum import Enum
import threading
import time

# Import technical indicators
try:
    import talib as ta
    TALIB_AVAILABLE = True
except ImportError:
    TALIB_AVAILABLE = False
    # Fallback implementations if talib is not available

logger = logging.getLogger(__name__)


class TradeDirection(Enum):
    """Trade direction enumeration"""
    CALL = "CALL"
    PUT = "PUT"
    NONE = "NONE"


class MarketCondition(Enum):
    """Market condition classification"""
    TRENDING_UP = "trending_up"
    TRENDING_DOWN = "trending_down"
    RANGING = "ranging"
    HIGH_VOLATILITY = "high_volatility"
    LOW_VOLATILITY = "low_volatility"
    BREAKOUT = "breakout"


@dataclass
class V75Config:
    """
    Configuration parameters for the V75 Expert Advisor.
    All parameters can be adjusted by the user.
    """
    # Core Trading Parameters
    lot_size: float = 1.0  # Default lot size for trades
    max_lot_size: float = 10.0  # Maximum lot size allowed
    min_lot_size: float = 0.35  # Minimum lot size for V75
    
    # Risk Management Parameters
    stop_loss_pips: float = 50.0  # Stop loss in pips
    take_profit_pips: float = 100.0  # Take profit in pips
    risk_per_trade_percent: float = 2.0  # Risk per trade as % of balance
    max_daily_loss_percent: float = 5.0  # Maximum daily loss as % of balance
    max_drawdown_percent: float = 10.0  # Maximum drawdown before stopping
    trailing_stop_pips: float = 30.0  # Trailing stop distance in pips
    use_trailing_stop: bool = True  # Enable/disable trailing stop
    
    # Position Management
    max_open_trades: int = 3  # Maximum concurrent open trades
    max_trades_per_hour: int = 10  # Rate limiting for trades
    cooldown_after_loss_seconds: int = 60  # Cooldown period after a loss
    
    # Strategy Parameters
    ema_fast_period: int = 9  # Fast EMA period
    ema_slow_period: int = 21  # Slow EMA period
    rsi_period: int = 14  # RSI period
    rsi_overbought: float = 70.0  # RSI overbought level
    rsi_oversold: float = 30.0  # RSI oversold level
    bollinger_period: int = 20  # Bollinger Bands period
    bollinger_std_dev: float = 2.0  # Bollinger Bands standard deviation
    atr_period: int = 14  # ATR period for volatility
    macd_fast: int = 12  # MACD fast period
    macd_slow: int = 26  # MACD slow period
    macd_signal: int = 9  # MACD signal period
    
    # V75-Specific Parameters
    volatility_threshold: float = 0.02  # Threshold for high volatility detection
    breakout_lookback: int = 20  # Candles to look back for breakout detection
    momentum_threshold: float = 0.5  # Momentum strength threshold
    
    # Trade Duration
    default_duration: int = 5  # Default trade duration in ticks
    duration_unit: str = "t"  # Duration unit (t=ticks, m=minutes)
    
    # Session Filters (V75 is 24/7 but some sessions are more volatile)
    trade_asian_session: bool = True
    trade_european_session: bool = True
    trade_american_session: bool = True
    
    # Debug/Logging
    enable_detailed_logging: bool = False
    
    def validate(self) -> bool:
        """Validate configuration parameters"""
        if self.lot_size < self.min_lot_size:
            raise ValueError(f"Lot size {self.lot_size} is below minimum {self.min_lot_size}")
        if self.lot_size > self.max_lot_size:
            raise ValueError(f"Lot size {self.lot_size} exceeds maximum {self.max_lot_size}")
        if self.risk_per_trade_percent <= 0 or self.risk_per_trade_percent > 10:
            raise ValueError("Risk per trade must be between 0 and 10 percent")
        if self.stop_loss_pips <= 0:
            raise ValueError("Stop loss must be positive")
        if self.take_profit_pips <= 0:
            raise ValueError("Take profit must be positive")
        if self.max_open_trades <= 0:
            raise ValueError("Max open trades must be positive")
        return True


@dataclass
class TradeSignal:
    """Represents a trading signal generated by the EA"""
    direction: TradeDirection
    strength: float  # Signal strength 0-1
    reason: str  # Human-readable reason for the signal
    entry_price: float
    stop_loss: float
    take_profit: float
    timestamp: datetime = field(default_factory=datetime.now)
    market_condition: MarketCondition = MarketCondition.RANGING


@dataclass
class TradeStatistics:
    """Trading statistics for performance tracking"""
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    total_profit: float = 0.0
    total_loss: float = 0.0
    max_drawdown: float = 0.0
    consecutive_wins: int = 0
    consecutive_losses: int = 0
    max_consecutive_wins: int = 0
    max_consecutive_losses: int = 0
    daily_profit: float = 0.0
    daily_loss: float = 0.0
    last_trade_time: Optional[datetime] = None
    start_balance: float = 0.0
    current_balance: float = 0.0
    
    @property
    def win_rate(self) -> float:
        """Calculate win rate percentage"""
        if self.total_trades == 0:
            return 0.0
        return (self.winning_trades / self.total_trades) * 100
    
    @property
    def profit_factor(self) -> float:
        """Calculate profit factor (gross profit / gross loss)"""
        if self.total_loss == 0:
            return float('inf') if self.total_profit > 0 else 0.0
        return abs(self.total_profit / self.total_loss)
    
    @property
    def net_profit(self) -> float:
        """Calculate net profit"""
        return self.total_profit - abs(self.total_loss)
    
    @property
    def daily_net(self) -> float:
        """Calculate daily net profit/loss"""
        return self.daily_profit - abs(self.daily_loss)


class TechnicalAnalysis:
    """Technical analysis indicators for V75"""
    
    @staticmethod
    def calculate_ema(prices: np.ndarray, period: int) -> Optional[np.ndarray]:
        """Calculate Exponential Moving Average"""
        if len(prices) < period:
            return None
        if TALIB_AVAILABLE:
            return ta.EMA(prices.astype(float), timeperiod=period)
        # Fallback calculation
        multiplier = 2 / (period + 1)
        ema = np.zeros_like(prices, dtype=float)
        ema[period - 1] = np.mean(prices[:period])
        for i in range(period, len(prices)):
            ema[i] = (prices[i] - ema[i - 1]) * multiplier + ema[i - 1]
        return ema
    
    @staticmethod
    def calculate_rsi(prices: np.ndarray, period: int = 14) -> Optional[np.ndarray]:
        """Calculate Relative Strength Index"""
        if len(prices) < period + 1:
            return None
        if TALIB_AVAILABLE:
            return ta.RSI(prices.astype(float), timeperiod=period)
        # Fallback calculation
        deltas = np.diff(prices)
        gains = np.where(deltas > 0, deltas, 0)
        losses = np.where(deltas < 0, -deltas, 0)
        
        avg_gain = np.zeros(len(prices))
        avg_loss = np.zeros(len(prices))
        avg_gain[period] = np.mean(gains[:period])
        avg_loss[period] = np.mean(losses[:period])
        
        for i in range(period + 1, len(prices)):
            avg_gain[i] = (avg_gain[i - 1] * (period - 1) + gains[i - 1]) / period
            avg_loss[i] = (avg_loss[i - 1] * (period - 1) + losses[i - 1]) / period
        
        rs = np.where(avg_loss != 0, avg_gain / avg_loss, 100)
        rsi = 100 - (100 / (1 + rs))
        return rsi
    
    @staticmethod
    def calculate_bollinger_bands(prices: np.ndarray, period: int = 20, 
                                   std_dev: float = 2.0) -> tuple:
        """Calculate Bollinger Bands"""
        if len(prices) < period:
            return None, None, None
        if TALIB_AVAILABLE:
            return ta.BBANDS(prices.astype(float), timeperiod=period, 
                            nbdevup=std_dev, nbdevdn=std_dev)
        # Fallback calculation
        middle = np.convolve(prices, np.ones(period) / period, mode='valid')
        middle = np.concatenate([np.full(period - 1, np.nan), middle])
        
        std = np.zeros_like(prices)
        for i in range(period - 1, len(prices)):
            std[i] = np.std(prices[i - period + 1:i + 1])
        
        upper = middle + std_dev * std
        lower = middle - std_dev * std
        return upper, middle, lower
    
    @staticmethod
    def calculate_macd(prices: np.ndarray, fast: int = 12, slow: int = 26, 
                       signal: int = 9) -> tuple:
        """Calculate MACD (Moving Average Convergence Divergence)"""
        if len(prices) < slow:
            return None, None, None
        if TALIB_AVAILABLE:
            return ta.MACD(prices.astype(float), fastperiod=fast, 
                          slowperiod=slow, signalperiod=signal)
        # Fallback calculation
        ema_fast = TechnicalAnalysis.calculate_ema(prices, fast)
        ema_slow = TechnicalAnalysis.calculate_ema(prices, slow)
        
        if ema_fast is None or ema_slow is None:
            return None, None, None
            
        macd_line = ema_fast - ema_slow
        signal_line = TechnicalAnalysis.calculate_ema(macd_line, signal)
        
        if signal_line is None:
            return None, None, None
            
        histogram = macd_line - signal_line
        return macd_line, signal_line, histogram
    
    @staticmethod
    def calculate_atr(high: np.ndarray, low: np.ndarray, close: np.ndarray, 
                      period: int = 14) -> Optional[np.ndarray]:
        """Calculate Average True Range for volatility measurement"""
        if len(close) < period + 1:
            return None
        if TALIB_AVAILABLE:
            return ta.ATR(high.astype(float), low.astype(float), 
                         close.astype(float), timeperiod=period)
        # Fallback calculation
        tr1 = high[1:] - low[1:]
        tr2 = np.abs(high[1:] - close[:-1])
        tr3 = np.abs(low[1:] - close[:-1])
        true_range = np.maximum(np.maximum(tr1, tr2), tr3)
        
        atr = np.zeros(len(close))
        atr[period] = np.mean(true_range[:period])
        for i in range(period + 1, len(close)):
            atr[i] = (atr[i - 1] * (period - 1) + true_range[i - 1]) / period
        return atr
    
    @staticmethod
    def calculate_momentum(prices: np.ndarray, period: int = 10) -> Optional[np.ndarray]:
        """Calculate price momentum"""
        if len(prices) < period:
            return None
        momentum = np.zeros(len(prices))
        for i in range(period, len(prices)):
            if prices[i - period] != 0:
                momentum[i] = ((prices[i] - prices[i - period]) / 
                              prices[i - period]) * 100
        return momentum


class V75ExpertAdvisor:
    """
    Expert Advisor for Volatility Index 75 (V75)
    
    This EA implements multiple trading strategies optimized for V75:
    1. EMA Crossover Strategy - Trend following
    2. RSI Reversal Strategy - Mean reversion
    3. Bollinger Band Breakout Strategy - Volatility breakout
    4. MACD Momentum Strategy - Momentum trading
    5. Combined Strategy - Uses all indicators for confirmation
    """
    
    # V75 Symbol
    SYMBOL = "R_75"
    
    def __init__(self, user_id: int, user_api, config: V75Config = None):
        """
        Initialize the V75 Expert Advisor
        
        Args:
            user_id: Telegram user ID
            user_api: DerivAPI instance for trading
            config: EA configuration parameters
        """
        self.user_id = user_id
        self.user_api = user_api
        self.config = config or V75Config()
        
        # Validate configuration
        self.config.validate()
        
        # Price data storage
        self.price_history: deque = deque(maxlen=500)  # Store more data for analysis
        self.high_history: deque = deque(maxlen=500)
        self.low_history: deque = deque(maxlen=500)
        
        # State management
        self.is_active = False
        self.is_trading_allowed = True
        self.current_market_condition = MarketCondition.RANGING
        
        # Trade tracking
        self.open_trades: List[Dict[str, Any]] = []
        self.trades_this_hour = 0
        self.last_hour_reset = datetime.now()
        self.last_trade_time: Optional[datetime] = None
        self.last_loss_time: Optional[datetime] = None
        
        # Statistics
        self.stats = TradeStatistics()
        
        # Signal callbacks
        self.on_signal_callback: Optional[Callable] = None
        self.on_trade_callback: Optional[Callable] = None
        
        logger.info(f"V75 Expert Advisor initialized for user {user_id}")
    
    async def add_price(self, price: float, high: float = None, low: float = None):
        """
        Add new price data to the EA
        
        Args:
            price: Current price (close)
            high: High price (if available)
            low: Low price (if available)
        """
        self.price_history.append(price)
        self.high_history.append(high if high else price)
        self.low_history.append(low if low else price)
        
        # Update market condition periodically
        if len(self.price_history) >= self.config.bollinger_period:
            self._update_market_condition()
    
    def _update_market_condition(self):
        """Analyze and update current market condition"""
        prices = np.array(list(self.price_history))
        
        # Calculate indicators for market condition
        ema_fast = TechnicalAnalysis.calculate_ema(prices, self.config.ema_fast_period)
        ema_slow = TechnicalAnalysis.calculate_ema(prices, self.config.ema_slow_period)
        
        if ema_fast is None or ema_slow is None:
            return
        
        # Trend detection
        if ema_fast[-1] > ema_slow[-1] * 1.001:  # 0.1% threshold
            trend = "up"
        elif ema_fast[-1] < ema_slow[-1] * 0.999:
            trend = "down"
        else:
            trend = "neutral"
        
        # Volatility detection using price range
        recent_prices = prices[-20:]
        price_range = (np.max(recent_prices) - np.min(recent_prices)) / np.mean(recent_prices)
        
        if price_range > self.config.volatility_threshold * 2:
            self.current_market_condition = MarketCondition.HIGH_VOLATILITY
        elif price_range < self.config.volatility_threshold * 0.5:
            self.current_market_condition = MarketCondition.LOW_VOLATILITY
        elif trend == "up":
            self.current_market_condition = MarketCondition.TRENDING_UP
        elif trend == "down":
            self.current_market_condition = MarketCondition.TRENDING_DOWN
        else:
            self.current_market_condition = MarketCondition.RANGING
    
    def _check_rate_limit(self) -> bool:
        """Check if we're within rate limits"""
        now = datetime.now()
        
        # Reset hourly counter if needed
        if (now - self.last_hour_reset).seconds >= 3600:
            self.trades_this_hour = 0
            self.last_hour_reset = now
        
        # Check hourly limit
        if self.trades_this_hour >= self.config.max_trades_per_hour:
            logger.debug("Rate limit reached: max trades per hour")
            return False
        
        # Check cooldown after loss
        if self.last_loss_time:
            cooldown_end = self.last_loss_time + timedelta(
                seconds=self.config.cooldown_after_loss_seconds
            )
            if now < cooldown_end:
                logger.debug("In cooldown period after loss")
                return False
        
        return True
    
    def _check_risk_limits(self) -> bool:
        """Check if we're within risk limits"""
        # Check daily loss limit
        daily_loss_percent = (abs(self.stats.daily_loss) / 
                             self.stats.start_balance * 100 
                             if self.stats.start_balance > 0 else 0)
        if daily_loss_percent >= self.config.max_daily_loss_percent:
            logger.warning("Daily loss limit reached")
            return False
        
        # Check max drawdown
        if self.stats.max_drawdown >= self.config.max_drawdown_percent:
            logger.warning("Maximum drawdown reached")
            return False
        
        # Check max open trades
        if len(self.open_trades) >= self.config.max_open_trades:
            logger.debug("Maximum open trades reached")
            return False
        
        return True
    
    async def analyze_ema_crossover(self) -> Optional[TradeSignal]:
        """
        EMA Crossover Strategy
        - Buy when fast EMA crosses above slow EMA
        - Sell when fast EMA crosses below slow EMA
        """
        prices = np.array(list(self.price_history))
        
        if len(prices) < self.config.ema_slow_period + 2:
            return None
        
        ema_fast = TechnicalAnalysis.calculate_ema(prices, self.config.ema_fast_period)
        ema_slow = TechnicalAnalysis.calculate_ema(prices, self.config.ema_slow_period)
        
        if ema_fast is None or ema_slow is None:
            return None
        
        # Check for crossover
        current_diff = ema_fast[-1] - ema_slow[-1]
        prev_diff = ema_fast[-2] - ema_slow[-2]
        
        current_price = prices[-1]
        
        # Bullish crossover
        if prev_diff <= 0 and current_diff > 0:
            sl = current_price - self.config.stop_loss_pips
            tp = current_price + self.config.take_profit_pips
            return TradeSignal(
                direction=TradeDirection.CALL,
                strength=min(abs(current_diff) / current_price * 1000, 1.0),
                reason="EMA Crossover: Fast EMA crossed above Slow EMA",
                entry_price=current_price,
                stop_loss=sl,
                take_profit=tp,
                market_condition=self.current_market_condition
            )
        
        # Bearish crossover
        if prev_diff >= 0 and current_diff < 0:
            sl = current_price + self.config.stop_loss_pips
            tp = current_price - self.config.take_profit_pips
            return TradeSignal(
                direction=TradeDirection.PUT,
                strength=min(abs(current_diff) / current_price * 1000, 1.0),
                reason="EMA Crossover: Fast EMA crossed below Slow EMA",
                entry_price=current_price,
                stop_loss=sl,
                take_profit=tp,
                market_condition=self.current_market_condition
            )
        
        return None
    
    async def analyze_rsi_reversal(self) -> Optional[TradeSignal]:
        """
        RSI Reversal Strategy
        - Buy when RSI exits oversold zone (crossing above 30)
        - Sell when RSI exits overbought zone (crossing below 70)
        """
        prices = np.array(list(self.price_history))
        
        if len(prices) < self.config.rsi_period + 2:
            return None
        
        rsi = TechnicalAnalysis.calculate_rsi(prices, self.config.rsi_period)
        
        if rsi is None:
            return None
        
        current_rsi = rsi[-1]
        prev_rsi = rsi[-2]
        current_price = prices[-1]
        
        # RSI exiting oversold - potential buy
        if prev_rsi < self.config.rsi_oversold and current_rsi >= self.config.rsi_oversold:
            sl = current_price - self.config.stop_loss_pips
            tp = current_price + self.config.take_profit_pips
            return TradeSignal(
                direction=TradeDirection.CALL,
                strength=(self.config.rsi_oversold - prev_rsi) / self.config.rsi_oversold,
                reason=f"RSI Reversal: RSI crossed above oversold ({current_rsi:.1f})",
                entry_price=current_price,
                stop_loss=sl,
                take_profit=tp,
                market_condition=self.current_market_condition
            )
        
        # RSI exiting overbought - potential sell
        if prev_rsi > self.config.rsi_overbought and current_rsi <= self.config.rsi_overbought:
            sl = current_price + self.config.stop_loss_pips
            tp = current_price - self.config.take_profit_pips
            return TradeSignal(
                direction=TradeDirection.PUT,
                strength=(prev_rsi - self.config.rsi_overbought) / (100 - self.config.rsi_overbought),
                reason=f"RSI Reversal: RSI crossed below overbought ({current_rsi:.1f})",
                entry_price=current_price,
                stop_loss=sl,
                take_profit=tp,
                market_condition=self.current_market_condition
            )
        
        return None
    
    async def analyze_bollinger_breakout(self) -> Optional[TradeSignal]:
        """
        Bollinger Band Breakout Strategy
        - Buy when price breaks above upper band with momentum
        - Sell when price breaks below lower band with momentum
        """
        prices = np.array(list(self.price_history))
        
        if len(prices) < self.config.bollinger_period + 2:
            return None
        
        upper, middle, lower = TechnicalAnalysis.calculate_bollinger_bands(
            prices, 
            self.config.bollinger_period, 
            self.config.bollinger_std_dev
        )
        
        if upper is None:
            return None
        
        current_price = prices[-1]
        prev_price = prices[-2]
        
        # Check for breakout with momentum confirmation
        momentum = TechnicalAnalysis.calculate_momentum(prices, 5)
        current_momentum = momentum[-1] if momentum is not None else 0
        
        # Bullish breakout
        if prev_price < upper[-2] and current_price > upper[-1] and current_momentum > 0:
            sl = middle[-1]  # Use middle band as stop loss
            tp = current_price + (current_price - middle[-1])  # Equal distance target
            return TradeSignal(
                direction=TradeDirection.CALL,
                strength=min(abs(current_momentum) / self.config.momentum_threshold, 1.0),
                reason="Bollinger Breakout: Price broke above upper band",
                entry_price=current_price,
                stop_loss=sl,
                take_profit=tp,
                market_condition=MarketCondition.BREAKOUT
            )
        
        # Bearish breakout
        if prev_price > lower[-2] and current_price < lower[-1] and current_momentum < 0:
            sl = middle[-1]  # Use middle band as stop loss
            tp = current_price - (middle[-1] - current_price)  # Equal distance target
            return TradeSignal(
                direction=TradeDirection.PUT,
                strength=min(abs(current_momentum) / self.config.momentum_threshold, 1.0),
                reason="Bollinger Breakout: Price broke below lower band",
                entry_price=current_price,
                stop_loss=sl,
                take_profit=tp,
                market_condition=MarketCondition.BREAKOUT
            )
        
        return None
    
    async def analyze_macd_momentum(self) -> Optional[TradeSignal]:
        """
        MACD Momentum Strategy
        - Buy when MACD line crosses above signal line with positive histogram
        - Sell when MACD line crosses below signal line with negative histogram
        """
        prices = np.array(list(self.price_history))
        
        if len(prices) < self.config.macd_slow + self.config.macd_signal:
            return None
        
        macd_line, signal_line, histogram = TechnicalAnalysis.calculate_macd(
            prices,
            self.config.macd_fast,
            self.config.macd_slow,
            self.config.macd_signal
        )
        
        if macd_line is None:
            return None
        
        current_price = prices[-1]
        
        # Check for MACD crossover
        if (macd_line[-2] <= signal_line[-2] and 
            macd_line[-1] > signal_line[-1] and 
            histogram[-1] > 0):
            sl = current_price - self.config.stop_loss_pips
            tp = current_price + self.config.take_profit_pips
            return TradeSignal(
                direction=TradeDirection.CALL,
                strength=min(abs(histogram[-1]) * 100, 1.0),
                reason="MACD Momentum: Bullish crossover with positive histogram",
                entry_price=current_price,
                stop_loss=sl,
                take_profit=tp,
                market_condition=self.current_market_condition
            )
        
        if (macd_line[-2] >= signal_line[-2] and 
            macd_line[-1] < signal_line[-1] and 
            histogram[-1] < 0):
            sl = current_price + self.config.stop_loss_pips
            tp = current_price - self.config.take_profit_pips
            return TradeSignal(
                direction=TradeDirection.PUT,
                strength=min(abs(histogram[-1]) * 100, 1.0),
                reason="MACD Momentum: Bearish crossover with negative histogram",
                entry_price=current_price,
                stop_loss=sl,
                take_profit=tp,
                market_condition=self.current_market_condition
            )
        
        return None
    
    async def analyze_combined_strategy(self) -> Optional[TradeSignal]:
        """
        Combined Strategy - Uses multiple indicators for confirmation
        Requires at least 2 indicators to agree for a signal
        """
        signals = []
        
        # Get all strategy signals
        ema_signal = await self.analyze_ema_crossover()
        rsi_signal = await self.analyze_rsi_reversal()
        bb_signal = await self.analyze_bollinger_breakout()
        macd_signal = await self.analyze_macd_momentum()
        
        for signal in [ema_signal, rsi_signal, bb_signal, macd_signal]:
            if signal and signal.direction != TradeDirection.NONE:
                signals.append(signal)
        
        if len(signals) < 2:
            return None
        
        # Count direction votes
        call_count = sum(1 for s in signals if s.direction == TradeDirection.CALL)
        put_count = sum(1 for s in signals if s.direction == TradeDirection.PUT)
        
        prices = np.array(list(self.price_history))
        current_price = prices[-1]
        
        if call_count >= 2:
            # Multiple indicators agree on CALL
            avg_strength = np.mean([s.strength for s in signals 
                                   if s.direction == TradeDirection.CALL])
            reasons = [s.reason for s in signals if s.direction == TradeDirection.CALL]
            sl = current_price - self.config.stop_loss_pips
            tp = current_price + self.config.take_profit_pips
            return TradeSignal(
                direction=TradeDirection.CALL,
                strength=avg_strength,
                reason=f"Combined Strategy ({call_count} confirmations): " + 
                       "; ".join(reasons[:2]),
                entry_price=current_price,
                stop_loss=sl,
                take_profit=tp,
                market_condition=self.current_market_condition
            )
        
        if put_count >= 2:
            # Multiple indicators agree on PUT
            avg_strength = np.mean([s.strength for s in signals 
                                   if s.direction == TradeDirection.PUT])
            reasons = [s.reason for s in signals if s.direction == TradeDirection.PUT]
            sl = current_price + self.config.stop_loss_pips
            tp = current_price - self.config.take_profit_pips
            return TradeSignal(
                direction=TradeDirection.PUT,
                strength=avg_strength,
                reason=f"Combined Strategy ({put_count} confirmations): " + 
                       "; ".join(reasons[:2]),
                entry_price=current_price,
                stop_loss=sl,
                take_profit=tp,
                market_condition=self.current_market_condition
            )
        
        return None
    
    async def should_buy_call(self) -> bool:
        """Check if we should buy a CALL contract"""
        if not self._check_rate_limit() or not self._check_risk_limits():
            return False
        
        signal = await self.analyze_combined_strategy()
        
        if signal and signal.direction == TradeDirection.CALL:
            if self.on_signal_callback:
                await self.on_signal_callback(signal)
            return signal.strength >= 0.5  # Minimum strength threshold
        
        return False
    
    async def should_buy_put(self) -> bool:
        """Check if we should buy a PUT contract"""
        if not self._check_rate_limit() or not self._check_risk_limits():
            return False
        
        signal = await self.analyze_combined_strategy()
        
        if signal and signal.direction == TradeDirection.PUT:
            if self.on_signal_callback:
                await self.on_signal_callback(signal)
            return signal.strength >= 0.5  # Minimum strength threshold
        
        return False
    
    async def get_signal(self) -> Optional[TradeSignal]:
        """Get current trading signal"""
        if not self._check_rate_limit() or not self._check_risk_limits():
            return None
        
        return await self.analyze_combined_strategy()
    
    async def place_trade(self, contract_type: str, amount: float = None, 
                         duration: int = None) -> bool:
        """
        Place a trade
        
        Args:
            contract_type: "CALL" or "PUT"
            amount: Trade amount (uses config lot_size if not specified)
            duration: Trade duration (uses config default_duration if not specified)
        """
        if amount is None:
            amount = self.config.lot_size
        if duration is None:
            duration = self.config.default_duration
        
        try:
            response = await self.user_api.buy_contract(
                contract_type, 
                self.SYMBOL, 
                amount, 
                duration, 
                self.config.duration_unit
            )
            
            if "buy" in response:
                self.trades_this_hour += 1
                self.last_trade_time = datetime.now()
                self.stats.total_trades += 1
                
                trade_info = {
                    "contract_id": response["buy"].get("contract_id"),
                    "type": contract_type,
                    "amount": amount,
                    "entry_time": datetime.now(),
                    "entry_price": response["buy"].get("start_time")
                }
                self.open_trades.append(trade_info)
                
                if self.on_trade_callback:
                    await self.on_trade_callback(trade_info)
                
                logger.info(f"Trade placed: {contract_type} ${amount} on {self.SYMBOL}")
                return True
            
            if "error" in response:
                logger.error(f"Trade error: {response['error'].get('message', 'Unknown')}")
            return False
            
        except Exception as e:
            logger.error(f"Trade placement error: {e}")
            return False
    
    def record_trade_result(self, profit: float, is_win: bool):
        """Record the result of a completed trade"""
        if is_win:
            self.stats.winning_trades += 1
            self.stats.total_profit += profit
            self.stats.daily_profit += profit
            self.stats.consecutive_wins += 1
            self.stats.consecutive_losses = 0
            self.stats.max_consecutive_wins = max(
                self.stats.max_consecutive_wins, 
                self.stats.consecutive_wins
            )
        else:
            self.stats.losing_trades += 1
            self.stats.total_loss += abs(profit)
            self.stats.daily_loss += abs(profit)
            self.stats.consecutive_losses += 1
            self.stats.consecutive_wins = 0
            self.stats.max_consecutive_losses = max(
                self.stats.max_consecutive_losses, 
                self.stats.consecutive_losses
            )
            self.last_loss_time = datetime.now()
        
        # Update drawdown
        if self.stats.start_balance > 0:
            current_dd = (self.stats.start_balance - self.stats.current_balance) / \
                        self.stats.start_balance * 100
            self.stats.max_drawdown = max(self.stats.max_drawdown, current_dd)
    
    def reset_daily_stats(self):
        """Reset daily statistics (call at start of each day)"""
        self.stats.daily_profit = 0.0
        self.stats.daily_loss = 0.0
        logger.info("Daily statistics reset")
    
    def get_stats(self) -> dict:
        """Get current trading statistics"""
        return {
            "total_trades": self.stats.total_trades,
            "winning_trades": self.stats.winning_trades,
            "losing_trades": self.stats.losing_trades,
            "win_rate": self.stats.win_rate,
            "profit_factor": self.stats.profit_factor,
            "net_profit": self.stats.net_profit,
            "max_drawdown": self.stats.max_drawdown,
            "max_consecutive_wins": self.stats.max_consecutive_wins,
            "max_consecutive_losses": self.stats.max_consecutive_losses,
            "daily_net": self.stats.daily_net,
            "market_condition": self.current_market_condition.value,
            "open_trades": len(self.open_trades),
            "trades_this_hour": self.trades_this_hour
        }
    
    def get_config_summary(self) -> str:
        """Get human-readable configuration summary"""
        return f"""
🤖 **V75 Expert Advisor Configuration**

**Trading Parameters:**
• Lot Size: {self.config.lot_size}
• Stop Loss: {self.config.stop_loss_pips} pips
• Take Profit: {self.config.take_profit_pips} pips
• Duration: {self.config.default_duration} {self.config.duration_unit}

**Risk Management:**
• Risk per Trade: {self.config.risk_per_trade_percent}%
• Max Daily Loss: {self.config.max_daily_loss_percent}%
• Max Drawdown: {self.config.max_drawdown_percent}%
• Max Open Trades: {self.config.max_open_trades}
• Trailing Stop: {'Enabled' if self.config.use_trailing_stop else 'Disabled'} ({self.config.trailing_stop_pips} pips)

**Strategy Parameters:**
• EMA Fast/Slow: {self.config.ema_fast_period}/{self.config.ema_slow_period}
• RSI Period: {self.config.rsi_period} (OB:{self.config.rsi_overbought}/OS:{self.config.rsi_oversold})
• Bollinger: {self.config.bollinger_period} period, {self.config.bollinger_std_dev} std dev
• MACD: {self.config.macd_fast}/{self.config.macd_slow}/{self.config.macd_signal}
"""


class V75EAManager:
    """Manager class for V75 Expert Advisors"""
    
    def __init__(self):
        self.active_eas: Dict[int, V75ExpertAdvisor] = {}  # user_id -> EA
        self.ea_threads: Dict[int, threading.Thread] = {}
    
    def create_ea(self, user_id: int, user_api, config: V75Config = None) -> V75ExpertAdvisor:
        """Create a new V75 EA for a user"""
        if user_id in self.active_eas:
            # Stop existing EA first
            self.stop_ea(user_id)
        
        ea = V75ExpertAdvisor(user_id, user_api, config)
        self.active_eas[user_id] = ea
        return ea
    
    def get_ea(self, user_id: int) -> Optional[V75ExpertAdvisor]:
        """Get EA for a user"""
        return self.active_eas.get(user_id)
    
    def start_ea(self, user_id: int, start_balance: float = 0) -> bool:
        """Start the EA for a user"""
        ea = self.active_eas.get(user_id)
        if not ea:
            return False
        
        ea.is_active = True
        ea.stats.start_balance = start_balance
        ea.stats.current_balance = start_balance
        
        # Start monitoring thread
        thread = threading.Thread(
            target=self._run_ea_monitoring,
            args=(user_id,),
            daemon=True
        )
        thread.start()
        self.ea_threads[user_id] = thread
        
        logger.info(f"V75 EA started for user {user_id}")
        return True
    
    def stop_ea(self, user_id: int) -> bool:
        """Stop the EA for a user"""
        ea = self.active_eas.get(user_id)
        if not ea:
            return False
        
        ea.is_active = False
        
        # Remove from tracking
        if user_id in self.ea_threads:
            del self.ea_threads[user_id]
        if user_id in self.active_eas:
            del self.active_eas[user_id]
        
        logger.info(f"V75 EA stopped for user {user_id}")
        return True
    
    def _run_ea_monitoring(self, user_id: int):
        """Background thread for EA price monitoring and signal generation"""
        ea = self.active_eas.get(user_id)
        if not ea:
            return
        
        while ea.is_active:
            try:
                # Create event loop for this thread
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
                
                # Get current price
                loop.run_until_complete(self._update_ea_price(ea))
                
                # Check for trading signals if we have enough data
                if len(ea.price_history) >= ea.config.ema_slow_period:
                    call_signal = loop.run_until_complete(ea.should_buy_call())
                    put_signal = loop.run_until_complete(ea.should_buy_put())
                    
                    if call_signal:
                        loop.run_until_complete(
                            ea.place_trade("CALL", ea.config.lot_size)
                        )
                    elif put_signal:
                        loop.run_until_complete(
                            ea.place_trade("PUT", ea.config.lot_size)
                        )
                
                loop.close()
                
                # Sleep between checks
                time.sleep(5)
                
            except Exception as e:
                logger.error(f"EA monitoring error for user {user_id}: {e}")
                time.sleep(10)
    
    async def _update_ea_price(self, ea: V75ExpertAdvisor):
        """Update price data for an EA"""
        try:
            response = await ea.user_api.get_ticks(ea.SYMBOL)
            if "tick" in response:
                price = response["tick"].get("quote", 0)
                await ea.add_price(price)
        except Exception as e:
            logger.error(f"Price update error: {e}")
    
    def get_all_stats(self) -> Dict[int, dict]:
        """Get stats for all active EAs"""
        return {uid: ea.get_stats() for uid, ea in self.active_eas.items()}


# Global EA manager instance
v75_ea_manager = V75EAManager()


# Convenience functions for integration with telegram_bot.py
def create_v75_ea(user_id: int, user_api, config: V75Config = None) -> V75ExpertAdvisor:
    """Create a V75 EA for a user"""
    return v75_ea_manager.create_ea(user_id, user_api, config)


def start_v75_ea(user_id: int, start_balance: float = 0) -> bool:
    """Start V75 EA for a user"""
    return v75_ea_manager.start_ea(user_id, start_balance)


def stop_v75_ea(user_id: int) -> bool:
    """Stop V75 EA for a user"""
    return v75_ea_manager.stop_ea(user_id)


def get_v75_ea(user_id: int) -> Optional[V75ExpertAdvisor]:
    """Get V75 EA for a user"""
    return v75_ea_manager.get_ea(user_id)


def get_v75_ea_stats(user_id: int) -> Optional[dict]:
    """Get V75 EA stats for a user"""
    ea = v75_ea_manager.get_ea(user_id)
    return ea.get_stats() if ea else None


if __name__ == "__main__":
    print("🤖 V75 Expert Advisor Module")
    print("=" * 50)
    print("\nFeatures:")
    print("• EMA Crossover Strategy")
    print("• RSI Reversal Strategy")
    print("• Bollinger Band Breakout Strategy")
    print("• MACD Momentum Strategy")
    print("• Combined Multi-Indicator Strategy")
    print("\nRisk Management:")
    print("• Stop Loss / Take Profit")
    print("• Trailing Stop")
    print("• Max Daily Loss Limit")
    print("• Max Drawdown Protection")
    print("• Rate Limiting")
    print("\nUsage:")
    print("  from v75_expert_advisor import create_v75_ea, start_v75_ea")
    print("  ea = create_v75_ea(user_id, user_api)")
    print("  start_v75_ea(user_id, balance)")
